// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: internal/asdp/asdp.proto

package asdp

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ConfigType identifies the type of configuration resource (analogous to xDS type_url).
type ConfigType int32

const (
	ConfigType_CONFIG_TYPE_UNSPECIFIED ConfigType = 0
	ConfigType_CONFIG_TYPE_AGENT       ConfigType = 1
	ConfigType_CONFIG_TYPE_TOOL        ConfigType = 2
	ConfigType_CONFIG_TYPE_SKILL       ConfigType = 3
	ConfigType_CONFIG_TYPE_OVERRIDE    ConfigType = 4
	ConfigType_CONFIG_TYPE_MODEL       ConfigType = 5
)

// Enum value maps for ConfigType.
var (
	ConfigType_name = map[int32]string{
		0: "CONFIG_TYPE_UNSPECIFIED",
		1: "CONFIG_TYPE_AGENT",
		2: "CONFIG_TYPE_TOOL",
		3: "CONFIG_TYPE_SKILL",
		4: "CONFIG_TYPE_OVERRIDE",
		5: "CONFIG_TYPE_MODEL",
	}
	ConfigType_value = map[string]int32{
		"CONFIG_TYPE_UNSPECIFIED": 0,
		"CONFIG_TYPE_AGENT":       1,
		"CONFIG_TYPE_TOOL":        2,
		"CONFIG_TYPE_SKILL":       3,
		"CONFIG_TYPE_OVERRIDE":    4,
		"CONFIG_TYPE_MODEL":       5,
	}
)

func (x ConfigType) Enum() *ConfigType {
	p := new(ConfigType)
	*p = x
	return p
}

func (x ConfigType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConfigType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_asdp_asdp_proto_enumTypes[0].Descriptor()
}

func (ConfigType) Type() protoreflect.EnumType {
	return &file_internal_asdp_asdp_proto_enumTypes[0]
}

func (x ConfigType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConfigType.Descriptor instead.
func (ConfigType) EnumDescriptor() ([]byte, []int) {
	return file_internal_asdp_asdp_proto_rawDescGZIP(), []int{0}
}

type Upstream struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Meta  *UpstreamMeta          `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Upstream_Connect
	//	*Upstream_ConfigAck
	//	*Upstream_SessionReport
	//	*Upstream_TeamEvent
	//	*Upstream_Heartbeat
	Payload       isUpstream_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Upstream) Reset() {
	*x = Upstream{}
	mi := &file_internal_asdp_asdp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Upstream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Upstream) ProtoMessage() {}

func (x *Upstream) ProtoReflect() protoreflect.Message {
	mi := &file_internal_asdp_asdp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Upstream.ProtoReflect.Descriptor instead.
func (*Upstream) Descriptor() ([]byte, []int) {
	return file_internal_asdp_asdp_proto_rawDescGZIP(), []int{0}
}

func (x *Upstream) GetMeta() *UpstreamMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *Upstream) GetPayload() isUpstream_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Upstream) GetConnect() *ConnectRequest {
	if x != nil {
		if x, ok := x.Payload.(*Upstream_Connect); ok {
			return x.Connect
		}
	}
	return nil
}

func (x *Upstream) GetConfigAck() *ConfigAck {
	if x != nil {
		if x, ok := x.Payload.(*Upstream_ConfigAck); ok {
			return x.ConfigAck
		}
	}
	return nil
}

func (x *Upstream) GetSessionReport() *SessionReport {
	if x != nil {
		if x, ok := x.Payload.(*Upstream_SessionReport); ok {
			return x.SessionReport
		}
	}
	return nil
}

func (x *Upstream) GetTeamEvent() *TeamEventReport {
	if x != nil {
		if x, ok := x.Payload.(*Upstream_TeamEvent); ok {
			return x.TeamEvent
		}
	}
	return nil
}

func (x *Upstream) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*Upstream_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

type isUpstream_Payload interface {
	isUpstream_Payload()
}

type Upstream_Connect struct {
	Connect *ConnectRequest `protobuf:"bytes,10,opt,name=connect,proto3,oneof"`
}

type Upstream_ConfigAck struct {
	ConfigAck *ConfigAck `protobuf:"bytes,11,opt,name=config_ack,json=configAck,proto3,oneof"`
}

type Upstream_SessionReport struct {
	SessionReport *SessionReport `protobuf:"bytes,12,opt,name=session_report,json=sessionReport,proto3,oneof"`
}

type Upstream_TeamEvent struct {
	TeamEvent *TeamEventReport `protobuf:"bytes,13,opt,name=team_event,json=teamEvent,proto3,oneof"`
}

type Upstream_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,14,opt,name=heartbeat,proto3,oneof"`
}

func (*Upstream_Connect) isUpstream_Payload() {}

func (*Upstream_ConfigAck) isUpstream_Payload() {}

func (*Upstream_SessionReport) isUpstream_Payload() {}

func (*Upstream_TeamEvent) isUpstream_Payload() {}

func (*Upstream_Heartbeat) isUpstream_Payload() {}

type UpstreamMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentName     string                 `protobuf:"bytes,1,opt,name=agent_name,json=agentName,proto3" json:"agent_name,omitempty"`
	InstanceId    string                 `protobuf:"bytes,2,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Namespace     string                 `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpstreamMeta) Reset() {
	*x = UpstreamMeta{}
	mi := &file_internal_asdp_asdp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpstreamMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpstreamMeta) ProtoMessage() {}

func (x *UpstreamMeta) ProtoReflect() protoreflect.Message {
	mi := &file_internal_asdp_asdp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpstreamMeta.ProtoReflect.Descriptor instead.
func (*UpstreamMeta) Descriptor() ([]byte, []int) {
	return file_internal_asdp_asdp_proto_rawDescGZIP(), []int{1}
}

func (x *UpstreamMeta) GetAgentName() string {
	if x != nil {
		return x.AgentName
	}
	return ""
}

func (x *UpstreamMeta) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *UpstreamMeta) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *UpstreamMeta) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// Handshake (sent on connection establish, analogous to xDS initial DiscoveryRequest)
type ConnectRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Runtime         string                 `protobuf:"bytes,1,opt,name=runtime,proto3" json:"runtime,omitempty"`
	SdkVersion      string                 `protobuf:"bytes,2,opt,name=sdk_version,json=sdkVersion,proto3" json:"sdk_version,omitempty"`
	Capabilities    []string               `protobuf:"bytes,3,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	SessionAffinity string                 `protobuf:"bytes,4,opt,name=session_affinity,json=sessionAffinity,proto3" json:"session_affinity,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ConnectRequest) Reset() {
	*x = ConnectRequest{}
	mi := &file_internal_asdp_asdp_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectRequest) ProtoMessage() {}

func (x *ConnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_asdp_asdp_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectRequest.ProtoReflect.Descriptor instead.
func (*ConnectRequest) Descriptor() ([]byte, []int) {
	return file_internal_asdp_asdp_proto_rawDescGZIP(), []int{2}
}

func (x *ConnectRequest) GetRuntime() string {
	if x != nil {
		return x.Runtime
	}
	return ""
}

func (x *ConnectRequest) GetSdkVersion() string {
	if x != nil {
		return x.SdkVersion
	}
	return ""
}

func (x *ConnectRequest) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *ConnectRequest) GetSessionAffinity() string {
	if x != nil {
		return x.SessionAffinity
	}
	return ""
}

// Config acknowledgement (analogous to xDS ACK/NACK)
type ConfigAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigType    ConfigType             `protobuf:"varint,1,opt,name=config_type,json=configType,proto3,enum=agentscope.protocol.v1.ConfigType" json:"config_type,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Nonce         string                 `protobuf:"bytes,3,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Accepted      bool                   `protobuf:"varint,4,opt,name=accepted,proto3" json:"accepted,omitempty"`
	RejectReason  string                 `protobuf:"bytes,5,opt,name=reject_reason,json=rejectReason,proto3" json:"reject_reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigAck) Reset() {
	*x = ConfigAck{}
	mi := &file_internal_asdp_asdp_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigAck) ProtoMessage() {}

func (x *ConfigAck) ProtoReflect() protoreflect.Message {
	mi := &file_internal_asdp_asdp_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigAck.ProtoReflect.Descriptor instead.
func (*ConfigAck) Descriptor() ([]byte, []int) {
	return file_internal_asdp_asdp_proto_rawDescGZIP(), []int{3}
}

func (x *ConfigAck) GetConfigType() ConfigType {
	if x != nil {
		return x.ConfigType
	}
	return ConfigType_CONFIG_TYPE_UNSPECIFIED
}

func (x *ConfigAck) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ConfigAck) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

func (x *ConfigAck) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *ConfigAck) GetRejectReason() string {
	if x != nil {
		return x.RejectReason
	}
	return ""
}

// Session state report (periodic batch, e.g. every 10s)
type SessionReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*SessionSnapshot     `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionReport) Reset() {
	*x = SessionReport{}
	mi := &file_internal_asdp_asdp_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionReport) ProtoMessage() {}

func (x *SessionReport) ProtoReflect() protoreflect.Message {
	mi := &file_internal_asdp_asdp_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionReport.ProtoReflect.Descriptor instead.
func (*SessionReport) Descriptor() ([]byte, []int) {
	return file_internal_asdp_asdp_proto_rawDescGZIP(), []int{4}
}

func (x *SessionReport) GetSessions() []*SessionSnapshot {
	if x != nil {
		return x.Sessions
	}
	return nil
}

type SessionSnapshot struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SessionId        string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Phase            string                 `protobuf:"bytes,2,opt,name=phase,proto3" json:"phase,omitempty"`
	MessageCount     int32                  `protobuf:"varint,3,opt,name=message_count,json=messageCount,proto3" json:"message_count,omitempty"`
	PromptTokens     int64                  `protobuf:"varint,4,opt,name=prompt_tokens,json=promptTokens,proto3" json:"prompt_tokens,omitempty"`
	CompletionTokens int64                  `protobuf:"varint,5,opt,name=completion_tokens,json=completionTokens,proto3" json:"completion_tokens,omitempty"`
	ContextPressure  float64                `protobuf:"fixed64,6,opt,name=context_pressure,json=contextPressure,proto3" json:"context_pressure,omitempty"`
	TaskSummary      *TaskSummary           `protobuf:"bytes,7,opt,name=task_summary,json=taskSummary,proto3" json:"task_summary,omitempty"`
	TeamId           string                 `protobuf:"bytes,8,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	TeamRole         string                 `protobuf:"bytes,9,opt,name=team_role,json=teamRole,proto3" json:"team_role,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SessionSnapshot) Reset() {
	*x = SessionSnapshot{}
	mi := &file_internal_asdp_asdp_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionSnapshot) ProtoMessage() {}

func (x *SessionSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_internal_asdp_asdp_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionSnapshot.ProtoReflect.Descriptor instead.
func (*SessionSnapshot) Descriptor() ([]byte, []int) {
	return file_internal_asdp_asdp_proto_rawDescGZIP(), []int{5}
}

func (x *SessionSnapshot) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionSnapshot) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *SessionSnapshot) GetMessageCount() int32 {
	if x != nil {
		return x.MessageCount
	}
	return 0
}

func (x *SessionSnapshot) GetPromptTokens() int64 {
	if x != nil {
		return x.PromptTokens
	}
	return 0
}

func (x *SessionSnapshot) GetCompletionTokens() int64 {
	if x != nil {
		return x.CompletionTokens
	}
	return 0
}

func (x *SessionSnapshot) GetContextPressure() float64 {
	if x != nil {
		return x.ContextPressure
	}
	return 0
}

func (x *SessionSnapshot) GetTaskSummary() *TaskSummary {
	if x != nil {
		return x.TaskSummary
	}
	return nil
}

func (x *SessionSnapshot) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *SessionSnapshot) GetTeamRole() string {
	if x != nil {
		return x.TeamRole
	}
	return ""
}

type TaskSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Pending       int32                  `protobuf:"varint,2,opt,name=pending,proto3" json:"pending,omitempty"`
	InProgress    int32                  `protobuf:"varint,3,opt,name=in_progress,json=inProgress,proto3" json:"in_progress,omitempty"`
	Completed     int32                  `protobuf:"varint,4,opt,name=completed,proto3" json:"completed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskSummary) Reset() {
	*x = TaskSummary{}
	mi := &file_internal_asdp_asdp_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskSummary) ProtoMessage() {}

func (x *TaskSummary) ProtoReflect() protoreflect.Message {
	mi := &file_internal_asdp_asdp_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskSummary.ProtoReflect.Descriptor instead.
func (*TaskSummary) Descriptor() ([]byte, []int) {
	return file_internal_asdp_asdp_proto_rawDescGZIP(), []int{6}
}

func (x *TaskSummary) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *TaskSummary) GetPending() int32 {
	if x != nil {
		return x.Pending
	}
	return 0
}

func (x *TaskSummary) GetInProgress() int32 {
	if x != nil {
		return x.InProgress
	}
	return 0
}

func (x *TaskSummary) GetCompleted() int32 {
	if x != nil {
		return x.Completed
	}
	return 0
}

// Team event report
type TeamEventReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        string                 `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	EventType     string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	MemberName    string                 `protobuf:"bytes,3,opt,name=member_name,json=memberName,proto3" json:"member_name,omitempty"`
	TaskId        string                 `protobuf:"bytes,4,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Detail        []byte                 `protobuf:"bytes,5,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TeamEventReport) Reset() {
	*x = TeamEventReport{}
	mi := &file_internal_asdp_asdp_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TeamEventReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeamEventReport) ProtoMessage() {}

func (x *TeamEventReport) ProtoReflect() protoreflect.Message {
	mi := &file_internal_asdp_asdp_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeamEventReport.ProtoReflect.Descriptor instead.
func (*TeamEventReport) Descriptor() ([]byte, []int) {
	return file_internal_asdp_asdp_proto_rawDescGZIP(), []int{7}
}

func (x *TeamEventReport) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *TeamEventReport) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *TeamEventReport) GetMemberName() string {
	if x != nil {
		return x.MemberName
	}
	return ""
}

func (x *TeamEventReport) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TeamEventReport) GetDetail() []byte {
	if x != nil {
		return x.Detail
	}
	return nil
}

// Heartbeat (bidirectional keepalive)
type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_internal_asdp_asdp_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_internal_asdp_asdp_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_internal_asdp_asdp_proto_rawDescGZIP(), []int{8}
}

func (x *Heartbeat) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// Instance health reported by data plane
type InstanceHealth struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Healthy        bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Reason         string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	ActiveSessions int32                  `protobuf:"varint,3,opt,name=active_sessions,json=activeSessions,proto3" json:"active_sessions,omitempty"`
	CpuUsage       float64                `protobuf:"fixed64,4,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	MemoryUsage    float64                `protobuf:"fixed64,5,opt,name=memory_usage,json=memoryUsage,proto3" json:"memory_usage,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InstanceHealth) Reset() {
	*x = InstanceHealth{}
	mi := &file_internal_asdp_asdp_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstanceHealth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstanceHealth) ProtoMessage() {}

func (x *InstanceHealth) ProtoReflect() protoreflect.Message {
	mi := &file_internal_asdp_asdp_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstanceHealth.ProtoReflect.Descriptor instead.
func (*InstanceHealth) Descriptor() ([]byte, []int) {
	return file_internal_asdp_asdp_proto_rawDescGZIP(), []int{9}
}

func (x *InstanceHealth) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *InstanceHealth) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *InstanceHealth) GetActiveSessions() int32 {
	if x != nil {
		return x.ActiveSessions
	}
	return 0
}

func (x *InstanceHealth) GetCpuUsage() float64 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *InstanceHealth) GetMemoryUsage() float64 {
	if x != nil {
		return x.MemoryUsage
	}
	return 0
}

type Downstream struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Downstream_ConnectAck
	//	*Downstream_ConfigPush
	//	*Downstream_SessionCmd
	//	*Downstream_TeamEvent
	//	*Downstream_Heartbeat
	Payload       isDownstream_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Downstream) Reset() {
	*x = Downstream{}
	mi := &file_internal_asdp_asdp_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Downstream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Downstream) ProtoMessage() {}

func (x *Downstream) ProtoReflect() protoreflect.Message {
	mi := &file_internal_asdp_asdp_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Downstream.ProtoReflect.Descriptor instead.
func (*Downstream) Descriptor() ([]byte, []int) {
	return file_internal_asdp_asdp_proto_rawDescGZIP(), []int{10}
}

func (x *Downstream) GetPayload() isDownstream_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Downstream) GetConnectAck() *ConnectResponse {
	if x != nil {
		if x, ok := x.Payload.(*Downstream_ConnectAck); ok {
			return x.ConnectAck
		}
	}
	return nil
}

func (x *Downstream) GetConfigPush() *ConfigPush {
	if x != nil {
		if x, ok := x.Payload.(*Downstream_ConfigPush); ok {
			return x.ConfigPush
		}
	}
	return nil
}

func (x *Downstream) GetSessionCmd() *SessionCommand {
	if x != nil {
		if x, ok := x.Payload.(*Downstream_SessionCmd); ok {
			return x.SessionCmd
		}
	}
	return nil
}

func (x *Downstream) GetTeamEvent() *TeamEvent {
	if x != nil {
		if x, ok := x.Payload.(*Downstream_TeamEvent); ok {
			return x.TeamEvent
		}
	}
	return nil
}

func (x *Downstream) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*Downstream_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

type isDownstream_Payload interface {
	isDownstream_Payload()
}

type Downstream_ConnectAck struct {
	ConnectAck *ConnectResponse `protobuf:"bytes,10,opt,name=connect_ack,json=connectAck,proto3,oneof"`
}

type Downstream_ConfigPush struct {
	ConfigPush *ConfigPush `protobuf:"bytes,11,opt,name=config_push,json=configPush,proto3,oneof"`
}

type Downstream_SessionCmd struct {
	SessionCmd *SessionCommand `protobuf:"bytes,12,opt,name=session_cmd,json=sessionCmd,proto3,oneof"`
}

type Downstream_TeamEvent struct {
	TeamEvent *TeamEvent `protobuf:"bytes,13,opt,name=team_event,json=teamEvent,proto3,oneof"`
}

type Downstream_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,14,opt,name=heartbeat,proto3,oneof"`
}

func (*Downstream_ConnectAck) isDownstream_Payload() {}

func (*Downstream_ConfigPush) isDownstream_Payload() {}

func (*Downstream_SessionCmd) isDownstream_Payload() {}

func (*Downstream_TeamEvent) isDownstream_Payload() {}

func (*Downstream_Heartbeat) isDownstream_Payload() {}

type ConnectResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Accepted            bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	RejectReason        string                 `protobuf:"bytes,2,opt,name=reject_reason,json=rejectReason,proto3" json:"reject_reason,omitempty"`
	ControlPlaneVersion string                 `protobuf:"bytes,3,opt,name=control_plane_version,json=controlPlaneVersion,proto3" json:"control_plane_version,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ConnectResponse) Reset() {
	*x = ConnectResponse{}
	mi := &file_internal_asdp_asdp_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectResponse) ProtoMessage() {}

func (x *ConnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_asdp_asdp_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectResponse.ProtoReflect.Descriptor instead.
func (*ConnectResponse) Descriptor() ([]byte, []int) {
	return file_internal_asdp_asdp_proto_rawDescGZIP(), []int{11}
}

func (x *ConnectResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *ConnectResponse) GetRejectReason() string {
	if x != nil {
		return x.RejectReason
	}
	return ""
}

func (x *ConnectResponse) GetControlPlaneVersion() string {
	if x != nil {
		return x.ControlPlaneVersion
	}
	return ""
}

// Config push (analogous to xDS DiscoveryResponse)
type ConfigPush struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigType    ConfigType             `protobuf:"varint,1,opt,name=config_type,json=configType,proto3,enum=agentscope.protocol.v1.ConfigType" json:"config_type,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Resources     []byte                 `protobuf:"bytes,3,opt,name=resources,proto3" json:"resources,omitempty"`
	Nonce         string                 `protobuf:"bytes,4,opt,name=nonce,proto3" json:"nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigPush) Reset() {
	*x = ConfigPush{}
	mi := &file_internal_asdp_asdp_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigPush) ProtoMessage() {}

func (x *ConfigPush) ProtoReflect() protoreflect.Message {
	mi := &file_internal_asdp_asdp_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigPush.ProtoReflect.Descriptor instead.
func (*ConfigPush) Descriptor() ([]byte, []int) {
	return file_internal_asdp_asdp_proto_rawDescGZIP(), []int{12}
}

func (x *ConfigPush) GetConfigType() ConfigType {
	if x != nil {
		return x.ConfigType
	}
	return ConfigType_CONFIG_TYPE_UNSPECIFIED
}

func (x *ConfigPush) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ConfigPush) GetResources() []byte {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *ConfigPush) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

type SessionCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Command       string                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	Params        []byte                 `protobuf:"bytes,3,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionCommand) Reset() {
	*x = SessionCommand{}
	mi := &file_internal_asdp_asdp_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionCommand) ProtoMessage() {}

func (x *SessionCommand) ProtoReflect() protoreflect.Message {
	mi := &file_internal_asdp_asdp_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionCommand.ProtoReflect.Descriptor instead.
func (*SessionCommand) Descriptor() ([]byte, []int) {
	return file_internal_asdp_asdp_proto_rawDescGZIP(), []int{13}
}

func (x *SessionCommand) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionCommand) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *SessionCommand) GetParams() []byte {
	if x != nil {
		return x.Params
	}
	return nil
}

type TeamEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        string                 `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	EventType     string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	MemberName    string                 `protobuf:"bytes,3,opt,name=member_name,json=memberName,proto3" json:"member_name,omitempty"`
	TaskId        string                 `protobuf:"bytes,4,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Payload       []byte                 `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	Timestamp     int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TeamEvent) Reset() {
	*x = TeamEvent{}
	mi := &file_internal_asdp_asdp_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TeamEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeamEvent) ProtoMessage() {}

func (x *TeamEvent) ProtoReflect() protoreflect.Message {
	mi := &file_internal_asdp_asdp_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeamEvent.ProtoReflect.Descriptor instead.
func (*TeamEvent) Descriptor() ([]byte, []int) {
	return file_internal_asdp_asdp_proto_rawDescGZIP(), []int{14}
}

func (x *TeamEvent) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *TeamEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *TeamEvent) GetMemberName() string {
	if x != nil {
		return x.MemberName
	}
	return ""
}

func (x *TeamEvent) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TeamEvent) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *TeamEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_internal_asdp_asdp_proto protoreflect.FileDescriptor

const file_internal_asdp_asdp_proto_rawDesc = "" +
	"\n" +
	"\x18internal/asdp/asdp.proto\x12\x16agentscope.protocol.v1\"\xb4\x03\n" +
	"\bUpstream\x128\n" +
	"\x04meta\x18\x01 \x01(\v2$.agentscope.protocol.v1.UpstreamMetaR\x04meta\x12B\n" +
	"\aconnect\x18\n" +
	" \x01(\v2&.agentscope.protocol.v1.ConnectRequestH\x00R\aconnect\x12B\n" +
	"\n" +
	"config_ack\x18\v \x01(\v2!.agentscope.protocol.v1.ConfigAckH\x00R\tconfigAck\x12N\n" +
	"\x0esession_report\x18\f \x01(\v2%.agentscope.protocol.v1.SessionReportH\x00R\rsessionReport\x12H\n" +
	"\n" +
	"team_event\x18\r \x01(\v2'.agentscope.protocol.v1.TeamEventReportH\x00R\tteamEvent\x12A\n" +
	"\theartbeat\x18\x0e \x01(\v2!.agentscope.protocol.v1.HeartbeatH\x00R\theartbeatB\t\n" +
	"\apayload\"\x8a\x01\n" +
	"\fUpstreamMeta\x12\x1d\n" +
	"\n" +
	"agent_name\x18\x01 \x01(\tR\tagentName\x12\x1f\n" +
	"\vinstance_id\x18\x02 \x01(\tR\n" +
	"instanceId\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"\x9a\x01\n" +
	"\x0eConnectRequest\x12\x18\n" +
	"\aruntime\x18\x01 \x01(\tR\aruntime\x12\x1f\n" +
	"\vsdk_version\x18\x02 \x01(\tR\n" +
	"sdkVersion\x12\"\n" +
	"\fcapabilities\x18\x03 \x03(\tR\fcapabilities\x12)\n" +
	"\x10session_affinity\x18\x04 \x01(\tR\x0fsessionAffinity\"\xc1\x01\n" +
	"\tConfigAck\x12C\n" +
	"\vconfig_type\x18\x01 \x01(\x0e2\".agentscope.protocol.v1.ConfigTypeR\n" +
	"configType\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x14\n" +
	"\x05nonce\x18\x03 \x01(\tR\x05nonce\x12\x1a\n" +
	"\baccepted\x18\x04 \x01(\bR\baccepted\x12#\n" +
	"\rreject_reason\x18\x05 \x01(\tR\frejectReason\"T\n" +
	"\rSessionReport\x12C\n" +
	"\bsessions\x18\x01 \x03(\v2'.agentscope.protocol.v1.SessionSnapshotR\bsessions\"\xe6\x02\n" +
	"\x0fSessionSnapshot\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05phase\x18\x02 \x01(\tR\x05phase\x12#\n" +
	"\rmessage_count\x18\x03 \x01(\x05R\fmessageCount\x12#\n" +
	"\rprompt_tokens\x18\x04 \x01(\x03R\fpromptTokens\x12+\n" +
	"\x11completion_tokens\x18\x05 \x01(\x03R\x10completionTokens\x12)\n" +
	"\x10context_pressure\x18\x06 \x01(\x01R\x0fcontextPressure\x12F\n" +
	"\ftask_summary\x18\a \x01(\v2#.agentscope.protocol.v1.TaskSummaryR\vtaskSummary\x12\x17\n" +
	"\ateam_id\x18\b \x01(\tR\x06teamId\x12\x1b\n" +
	"\tteam_role\x18\t \x01(\tR\bteamRole\"|\n" +
	"\vTaskSummary\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12\x18\n" +
	"\apending\x18\x02 \x01(\x05R\apending\x12\x1f\n" +
	"\vin_progress\x18\x03 \x01(\x05R\n" +
	"inProgress\x12\x1c\n" +
	"\tcompleted\x18\x04 \x01(\x05R\tcompleted\"\x9b\x01\n" +
	"\x0fTeamEventReport\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\tR\x06teamId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12\x1f\n" +
	"\vmember_name\x18\x03 \x01(\tR\n" +
	"memberName\x12\x17\n" +
	"\atask_id\x18\x04 \x01(\tR\x06taskId\x12\x16\n" +
	"\x06detail\x18\x05 \x01(\fR\x06detail\")\n" +
	"\tHeartbeat\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\"\xab\x01\n" +
	"\x0eInstanceHealth\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12'\n" +
	"\x0factive_sessions\x18\x03 \x01(\x05R\x0eactiveSessions\x12\x1b\n" +
	"\tcpu_usage\x18\x04 \x01(\x01R\bcpuUsage\x12!\n" +
	"\fmemory_usage\x18\x05 \x01(\x01R\vmemoryUsage\"\xfc\x02\n" +
	"\n" +
	"Downstream\x12J\n" +
	"\vconnect_ack\x18\n" +
	" \x01(\v2'.agentscope.protocol.v1.ConnectResponseH\x00R\n" +
	"connectAck\x12E\n" +
	"\vconfig_push\x18\v \x01(\v2\".agentscope.protocol.v1.ConfigPushH\x00R\n" +
	"configPush\x12I\n" +
	"\vsession_cmd\x18\f \x01(\v2&.agentscope.protocol.v1.SessionCommandH\x00R\n" +
	"sessionCmd\x12B\n" +
	"\n" +
	"team_event\x18\r \x01(\v2!.agentscope.protocol.v1.TeamEventH\x00R\tteamEvent\x12A\n" +
	"\theartbeat\x18\x0e \x01(\v2!.agentscope.protocol.v1.HeartbeatH\x00R\theartbeatB\t\n" +
	"\apayload\"\x86\x01\n" +
	"\x0fConnectResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12#\n" +
	"\rreject_reason\x18\x02 \x01(\tR\frejectReason\x122\n" +
	"\x15control_plane_version\x18\x03 \x01(\tR\x13controlPlaneVersion\"\x9f\x01\n" +
	"\n" +
	"ConfigPush\x12C\n" +
	"\vconfig_type\x18\x01 \x01(\x0e2\".agentscope.protocol.v1.ConfigTypeR\n" +
	"configType\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1c\n" +
	"\tresources\x18\x03 \x01(\fR\tresources\x12\x14\n" +
	"\x05nonce\x18\x04 \x01(\tR\x05nonce\"a\n" +
	"\x0eSessionCommand\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\x12\x16\n" +
	"\x06params\x18\x03 \x01(\fR\x06params\"\xb5\x01\n" +
	"\tTeamEvent\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\tR\x06teamId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12\x1f\n" +
	"\vmember_name\x18\x03 \x01(\tR\n" +
	"memberName\x12\x17\n" +
	"\atask_id\x18\x04 \x01(\tR\x06taskId\x12\x18\n" +
	"\apayload\x18\x05 \x01(\fR\apayload\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp*\x9e\x01\n" +
	"\n" +
	"ConfigType\x12\x1b\n" +
	"\x17CONFIG_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11CONFIG_TYPE_AGENT\x10\x01\x12\x14\n" +
	"\x10CONFIG_TYPE_TOOL\x10\x02\x12\x15\n" +
	"\x11CONFIG_TYPE_SKILL\x10\x03\x12\x18\n" +
	"\x14CONFIG_TYPE_OVERRIDE\x10\x04\x12\x15\n" +
	"\x11CONFIG_TYPE_MODEL\x10\x052l\n" +
	"\x15AgentDataPlaneService\x12S\n" +
	"\aConnect\x12 .agentscope.protocol.v1.Upstream\x1a\".agentscope.protocol.v1.Downstream(\x010\x01BAZ?github.com/spring-ai-alibaba/aistio/internal/asdpb\x06proto3"

var (
	file_internal_asdp_asdp_proto_rawDescOnce sync.Once
	file_internal_asdp_asdp_proto_rawDescData []byte
)

func file_internal_asdp_asdp_proto_rawDescGZIP() []byte {
	file_internal_asdp_asdp_proto_rawDescOnce.Do(func() {
		file_internal_asdp_asdp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_asdp_asdp_proto_rawDesc), len(file_internal_asdp_asdp_proto_rawDesc)))
	})
	return file_internal_asdp_asdp_proto_rawDescData
}

var file_internal_asdp_asdp_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_asdp_asdp_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_internal_asdp_asdp_proto_goTypes = []any{
	(ConfigType)(0),         // 0: agentscope.protocol.v1.ConfigType
	(*Upstream)(nil),        // 1: agentscope.protocol.v1.Upstream
	(*UpstreamMeta)(nil),    // 2: agentscope.protocol.v1.UpstreamMeta
	(*ConnectRequest)(nil),  // 3: agentscope.protocol.v1.ConnectRequest
	(*ConfigAck)(nil),       // 4: agentscope.protocol.v1.ConfigAck
	(*SessionReport)(nil),   // 5: agentscope.protocol.v1.SessionReport
	(*SessionSnapshot)(nil), // 6: agentscope.protocol.v1.SessionSnapshot
	(*TaskSummary)(nil),     // 7: agentscope.protocol.v1.TaskSummary
	(*TeamEventReport)(nil), // 8: agentscope.protocol.v1.TeamEventReport
	(*Heartbeat)(nil),       // 9: agentscope.protocol.v1.Heartbeat
	(*InstanceHealth)(nil),  // 10: agentscope.protocol.v1.InstanceHealth
	(*Downstream)(nil),      // 11: agentscope.protocol.v1.Downstream
	(*ConnectResponse)(nil), // 12: agentscope.protocol.v1.ConnectResponse
	(*ConfigPush)(nil),      // 13: agentscope.protocol.v1.ConfigPush
	(*SessionCommand)(nil),  // 14: agentscope.protocol.v1.SessionCommand
	(*TeamEvent)(nil),       // 15: agentscope.protocol.v1.TeamEvent
}
var file_internal_asdp_asdp_proto_depIdxs = []int32{
	2,  // 0: agentscope.protocol.v1.Upstream.meta:type_name -> agentscope.protocol.v1.UpstreamMeta
	3,  // 1: agentscope.protocol.v1.Upstream.connect:type_name -> agentscope.protocol.v1.ConnectRequest
	4,  // 2: agentscope.protocol.v1.Upstream.config_ack:type_name -> agentscope.protocol.v1.ConfigAck
	5,  // 3: agentscope.protocol.v1.Upstream.session_report:type_name -> agentscope.protocol.v1.SessionReport
	8,  // 4: agentscope.protocol.v1.Upstream.team_event:type_name -> agentscope.protocol.v1.TeamEventReport
	9,  // 5: agentscope.protocol.v1.Upstream.heartbeat:type_name -> agentscope.protocol.v1.Heartbeat
	0,  // 6: agentscope.protocol.v1.ConfigAck.config_type:type_name -> agentscope.protocol.v1.ConfigType
	6,  // 7: agentscope.protocol.v1.SessionReport.sessions:type_name -> agentscope.protocol.v1.SessionSnapshot
	7,  // 8: agentscope.protocol.v1.SessionSnapshot.task_summary:type_name -> agentscope.protocol.v1.TaskSummary
	12, // 9: agentscope.protocol.v1.Downstream.connect_ack:type_name -> agentscope.protocol.v1.ConnectResponse
	13, // 10: agentscope.protocol.v1.Downstream.config_push:type_name -> agentscope.protocol.v1.ConfigPush
	14, // 11: agentscope.protocol.v1.Downstream.session_cmd:type_name -> agentscope.protocol.v1.SessionCommand
	15, // 12: agentscope.protocol.v1.Downstream.team_event:type_name -> agentscope.protocol.v1.TeamEvent
	9,  // 13: agentscope.protocol.v1.Downstream.heartbeat:type_name -> agentscope.protocol.v1.Heartbeat
	0,  // 14: agentscope.protocol.v1.ConfigPush.config_type:type_name -> agentscope.protocol.v1.ConfigType
	1,  // 15: agentscope.protocol.v1.AgentDataPlaneService.Connect:input_type -> agentscope.protocol.v1.Upstream
	11, // 16: agentscope.protocol.v1.AgentDataPlaneService.Connect:output_type -> agentscope.protocol.v1.Downstream
	16, // [16:17] is the sub-list for method output_type
	15, // [15:16] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_internal_asdp_asdp_proto_init() }
func file_internal_asdp_asdp_proto_init() {
	if File_internal_asdp_asdp_proto != nil {
		return
	}
	file_internal_asdp_asdp_proto_msgTypes[0].OneofWrappers = []any{
		(*Upstream_Connect)(nil),
		(*Upstream_ConfigAck)(nil),
		(*Upstream_SessionReport)(nil),
		(*Upstream_TeamEvent)(nil),
		(*Upstream_Heartbeat)(nil),
	}
	file_internal_asdp_asdp_proto_msgTypes[10].OneofWrappers = []any{
		(*Downstream_ConnectAck)(nil),
		(*Downstream_ConfigPush)(nil),
		(*Downstream_SessionCmd)(nil),
		(*Downstream_TeamEvent)(nil),
		(*Downstream_Heartbeat)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_asdp_asdp_proto_rawDesc), len(file_internal_asdp_asdp_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_asdp_asdp_proto_goTypes,
		DependencyIndexes: file_internal_asdp_asdp_proto_depIdxs,
		EnumInfos:         file_internal_asdp_asdp_proto_enumTypes,
		MessageInfos:      file_internal_asdp_asdp_proto_msgTypes,
	}.Build()
	File_internal_asdp_asdp_proto = out.File
	file_internal_asdp_asdp_proto_goTypes = nil
	file_internal_asdp_asdp_proto_depIdxs = nil
}
